---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.13
    commands:
      - go build

  - name: test
    image: golang:1.13
    commands:
      - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

  - name: coverage
    image: plugins/codecov
    settings:
      token: 743b62e8-5e6a-4535-a8df-f1d69f9e1261
      files:
        - coverage.txt

  - name: publish
    image: plugins/docker
    settings:
      repo: ghcr.io/monkiato/guardian-admin
      registry: ghcr.io
      tags: ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*
