version: '2'

services:
  guardian-admin:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: pg
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: changeme
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - ./.docker/postgres/data:/data/postgres
    restart: always

  pgadmin:
    links:
      - pg:postgres
    image: fenglc/pgadmin4
    volumes:
       - ./.docker/postgres/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    restart: always
